version: "3.8"

services:
  falcon_mapping:
    build: .
    container_name: falcon_mapping

    network_mode: host
    ipc: host

    environment:
      - DISPLAY=${DISPLAY}

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./workspace:/workspace

    stdin_open: true
    tty: true